#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import methods
#' @importFrom assertthat assert_that
#' @importFrom data.table :=
#' @importFrom data.table .BY
#' @importFrom data.table .EACHI
#' @importFrom data.table .GRP
#' @importFrom data.table .I
#' @importFrom data.table .N
#' @importFrom data.table .NGRP
#' @importFrom data.table .SD
#' @importFrom data.table as.data.table
#' @importFrom data.table copy
#' @importFrom data.table data.table
#' @importFrom data.table rbindlist
#' @importFrom data.table set
#' @importFrom data.table setkey
#' @importFrom dplyr group_by
#' @importFrom dplyr mutate
#' @importFrom dplyr summarise
#' @importFrom future.apply future_lapply
#' @importFrom ggforce facet_wrap_paginate
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_errorbar
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 guide_axis
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 ylab
#' @importFrom landscapemetrics get_patches
#' @importFrom landscapemetrics lsm_c_ai
#' @importFrom landscapemetrics lsm_c_area_cv
#' @importFrom landscapemetrics lsm_c_area_mn
#' @importFrom landscapemetrics lsm_c_area_sd
#' @importFrom landscapemetrics lsm_c_ca
#' @importFrom landscapemetrics lsm_l_area_mn
#' @importFrom landscapemetrics lsm_l_area_sd
#' @importFrom landscapemetrics lsm_l_cohesion
#' @importFrom landscapemetrics lsm_l_condent
#' @importFrom landscapemetrics lsm_l_core_cv
#' @importFrom landscapemetrics lsm_l_core_mn
#' @importFrom landscapemetrics lsm_l_core_sd
#' @importFrom landscapemetrics lsm_l_ed
#' @importFrom landscapemetrics lsm_l_iji
#' @importFrom landscapemetrics lsm_p_area
#' @importFrom pemisc optimalClusterNum
#' @importFrom purrr transpose
#' @importFrom qs qread
#' @importFrom raster crop
#' @importFrom raster levels
#' @importFrom raster mask
#' @importFrom raster raster
#' @importFrom sf st_as_sf
#' @importFrom sf st_read
#' @importFrom SpaDES.tools rasterizeReduced
#' @importFrom stats median
#' @importFrom stats na.omit
#' @importFrom stats qt
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom terra classify
#' @importFrom terra compareGeom
#' @importFrom terra crop
#' @importFrom terra levels
#' @importFrom terra mask
#' @importFrom terra ncell
#' @importFrom terra rast
#' @importFrom terra rasterize
#' @importFrom terra values
#' @importFrom tools file_path_sans_ext
#' @importFrom utils globalVariables
## usethis namespace: end
NULL
